name: TiltGrabbing

required-object-info:
  tool: true
  target-object: true
  task: grabbing_book

# The following motion phases will be executed in a sequence
motion-phases:
  - name: Position Above
    # Giskard file
    file: tilting_position_above.yaml
    # Stop conditions
    stop:
      # When measured gripper velocity drops below this threshold
      measured-velocity-min-threshold: 0.02
      # When desired (set by the controller) gripper velocity drops below this threshold
      desired-velocity-min-threshold: 0.02
      # Stop on contact
      contact: false
      # Ignore stop conditions until the distance 
      # from the target configuration is less than this
      activation-distance: 0.15
  - name: Position infront one
    file: tilting_position_front.yaml
    stop:
      measured-velocity-min-threshold: 0.02
      desired-velocity-min-threshold: 0.02
      contact: false
      activation-distance: 0.15
  - name: Position infront two
    file: tilting_position_front_2.yaml
    stop:
      measured-velocity-min-threshold: 0.02
      desired-velocity-min-threshold: 0.02
      contact: false
      activation-distance: 0.15
  - name: Touch top
    file: tilting_touch_top.yaml
    stop:
      measured-velocity-min-threshold: 0.01
      desired-velocity-min-threshold: 0.01
      contact: true
      activation-distance: 0.15
  - name: Tilt
    file: tilting_tilt.yaml
    stop:
      measured-velocity-min-threshold: 0.002
      desired-velocity-min-threshold: 0.002
      contact: false
      activation-distance: 0.15
  - name: Grab
    file: tilting_grab.yaml
    stop:
      measured-velocity-min-threshold: 0.002
      desired-velocity-min-threshold: 0.002
      contact: false
      activation-distance: 0.5
  - name: Lift finger
    file: tilting_position_above.yaml
    stop:
      measured-velocity-min-threshold: 0.002
      desired-velocity-min-threshold: 0.002
      contact: false
      activation-distance: 0.15
  - name: Pull
    file: tilting_pull.yaml
    stop:
      measured-velocity-min-threshold: 0.002
      desired-velocity-min-threshold: 0.002
      contact: false
      activation-distance: 0.15